### PR TITLE
14.x CMake: Suppress MSVC warnings

### PR DESCRIPTION
**Pull request by whyman**

### CODE REVIEW

**Comment by Vollstrecker** [comment]
Maybe this would be better set private and added to the other lib also. If someone chainbuilds his stuff with the lib, this would propagate to their stuff and maybe he doesn't want this.

**Comment by whyman** [comment]
Perhaps, this is just a backport from master.

**Comment by Vollstrecker** [comment]
I remember, so we should either change that on master and backport then, or merge and fix this and forwardport it.

**Review by Vollstrecker — COMMENTED** [review]
I don't get it., empty line on 24, _CRT* still public, and I can't remember script_support was removed.

Am I right that your'e still trying to get everything in order?

**Pull request closed without merging**
