### PR TITLE
Fix build in mingw

### PR DESCRIPTION
**Pull request by Biswa96**

### CODE REVIEW

**Comment by Biswa96** [comment]
One issue that got recently is this:

```sh
F:/pupnp/bin/upnp/inc/upnpconfig.h:67: warning: "UPNP_LARGEFILE_SENSITIVE" redefined
   67 | #define UPNP_LARGEFILE_SENSITIVE
      |
In file included from F:/pupnp/upnp/test/test_internal.c:1:
F:/pupnp/bin/autoconfig.h:2: note: this is the location of the previous definition
    2 | #define UPNP_LARGEFILE_SENSITIVE 1
      |
```

I am not sure how to troubleshoot that.

**Comment by whyman** [comment]
FYI @Vollstrecker

**Comment by mrjimenez** [comment]
> One issue that got recently is this:
> 
> ```shell
> F:/pupnp/bin/upnp/inc/upnpconfig.h:67: warning: "UPNP_LARGEFILE_SENSITIVE" redefined
>    67 | #define UPNP_LARGEFILE_SENSITIVE
>       |
> In file included from F:/pupnp/upnp/test/test_internal.c:1:
> F:/pupnp/bin/autoconfig.h:2: note: this is the location of the previous definition
>     2 | #define UPNP_LARGEFILE_SENSITIVE 1
>       |
> ```
> 
> I am not sure how to troubleshoot that.

Maybe you have old autotools? This file is generated from configure, and in my system all `#defines` are generated with `1`, they are not empty. I have:

```bash
autoconf-2.69-17.31.noarch
automake-1.16.5-1.3.noarch
```

**Comment by Vollstrecker** [comment]
No he's right, compare [Line 67](https://github.com/pupnp/pupnp/blob/bac86e9fccf7e108501119fa4f9fb6e1dc078bde/upnp/inc/upnpconfig.h.cm#L67) and [Line 80](https://github.com/pupnp/pupnp/blob/bac86e9fccf7e108501119fa4f9fb6e1dc078bde/upnp/inc/upnpconfig.h.cm#L80)

I just want to get mingw running in my win-vm to see what else happens there unexpected, but the change could be done anyway.

**Comment by mrjimenez** [comment]
> No he's right, compare [Line 67](https://github.com/pupnp/pupnp/blob/bac86e9fccf7e108501119fa4f9fb6e1dc078bde/upnp/inc/upnpconfig.h.cm#L67) and [Line 80](https://github.com/pupnp/pupnp/blob/bac86e9fccf7e108501119fa4f9fb6e1dc078bde/upnp/inc/upnpconfig.h.cm#L80)

Oh, I see, my bad.

> I just want to get mingw running in my win-vm to see what else happens there unexpected, but the change could be done anyway.

So, just to be sure, you mean we can commit it, right?

**Comment by Vollstrecker** [comment]
No, I think this one was my fault.

I guess we can commit, I think if a user of mingw suggests that patch which should only influence mingw, we can trust him. I'm going to fix the redef later today. Maybe someone who knows how to do it can include mingw in our tests.

**Comment by Biswa96** [comment]
> Maybe someone who knows how to do it can include mingw in our tests.

Thank you all. If you want I can try to add msys2/mingw build environment in GitHub Actions CI.

**Comment by mrjimenez** [comment]
Sure, that would be great!

**Pull request merged**
