### PR TITLE
CI: Add msys2/mingw builds

### PR DESCRIPTION
**Pull request by Biswa96**

### CODE REVIEW

**Comment by Biswa96** [comment]
This is just a basic build workflow in msys2. This can be extended with more options.

**Comment by mrjimenez** [comment]
Feel free to improve it.

Thanks!

**Comment by mrjimenez** [comment]
@Vollstrecker , @whyman , @Biswa96 ,

Anyone can think of a reason not to copy ccpp.yml from master to branch-1.14.x? Because I am really tempted to do so...

**Comment by Vollstrecker** [comment]
I guess the script-file called in Lines 52 and 81 will give you an error as it is just not there, but without the lines it's just configuring, building and testing, so this is something that has to work.

**Pull request merged**
