### PR TITLE
fix 32-bit format warnings

### PR DESCRIPTION
**Pull request by neheb**
Seems this PRIzu takes size_t, not unsigned long.

### CODE REVIEW

**Comment by AlaricSenat** [comment]
This is reintroducing the opposite MSVC warnings (see the CI):
```
 D:\a\pupnp\pupnp\upnp\src\genlib\net\http\httpreadwrite.c(632,7): warning C4477: 'snprintf' : format string '%lx' requires an argument of type 'unsigned long', but variadic argument 1 has type 'size_t' [D:\a\pupnp\pupnp\build\upnp\upnp_shared.vcxproj]
```

We might want to fix the `PRIzu` defined in the `UpnpGlobal` header file.

**Comment by neheb** [comment]
@AlaricSenat lx is for compatibility with MSVC less than 2015?

**Comment by AlaricSenat** [comment]
It's definitely for compatibility with an old MSVC version, I'm not exactly sure which one, if you could link us evidence that it's the 2015 one it would be great! :)

IMO, the correct fix would be to use `%zu` for MSVC higher than 2015 with a  `_MSC_VER` check.

**Comment by neheb** [comment]
https://learn.microsoft.com/en-us/cpp/overview/visual-cpp-language-conformance?view=msvc-170 lists improvement in format functions, but doesn't explicitly say c99 formats.

**Comment by neheb** [comment]
As an aside, MinGW needs fixing too. Probably different PR.

**Pull request merged**
