### PR TITLE
Build only one lib for debug and release

### PR DESCRIPTION
**Pull request by Vollstrecker**
Hi,

I found an easy solution. I prefixed all functions like UpnpGetLogFile to Debug_UpnpGetLogFile, then added their signatures to upnpdebug.h, and then if debug is defined, define UpnpGetLogFile to Debug_UpnpGetLogFile.

### CODE REVIEW

**Comment by mrjimenez** [comment]
Hi Vollstrecker,

There is a problem with your pull request, the last time it also happened and I had quite some work fixing it by hand, but now it has repeated, could you please see if you are doing something different?

All your commits keep reappearing and there are merges in your branch and that makes rebase and merge impossible.

Also, do notice that your current commit fails checks:
```bash
make[4]: Entering directory '/home/runner/work/pupnp/pupnp/libupnp-1.14.1/_build/sub/upnp'
  CC       test/test_init.o
  CCLD     test_init
test/test_init.o: In function `main':
/home/runner/work/pupnp/pupnp/libupnp-1.14.1/_build/sub/upnp/../../../upnp/test/test_init.c:108: undefined reference to `Debug_UpnpSetLogFileNames'
collect2: error: ld returned 1 exit status
Makefile:1114: recipe for target 'test_init' failed
make[4]: *** [test_init] Error 1
make[4]: Leaving directory '/home/runner/work/pupnp/pupnp/libupnp-1.14.1/_build/sub/upnp'
make[3]: *** [check-am] Error 2
Makefile:2003: recipe for target 'check-am' failed
make[3]: Leaving directory '/home/runner/work/pupnp/pupnp/libupnp-1.14.1/_build/sub/upnp'
make[2]: *** [check-recursive] Error 1
make[1]: *** [check-recursive] Error 1
Makefile:1671: recipe for target 'check-recursive' failed
make[2]: Leaving directory '/home/runner/work/pupnp/pupnp/libupnp-1.14.1/_build/sub/upnp'
Makefile:515: recipe for target 'check-recursive' failed
make[1]: Leaving directory '/home/runner/work/pupnp/pupnp/libupnp-1.14.1/_build/sub'
make: *** [distcheck] Error 1
Makefile:720: recipe for target 'distcheck' failed
```

Best regards,
Marcelo.

**Comment by Vollstrecker** [comment]
Sorry, maybe this comes from merging the merged PR back instead of forking the repo again. I'll try after this one some other methods.

I can't reproduce this error. make distcheck works regardless of -enable-debug set or not. Is this the only one that fails to get redirected properly?

**Comment by Vollstrecker** [comment]
Strange, with cmake it works as expected. I forgot to move the source in Makefile.am, that would cause it to fail non-debug. But it fails in both.

What libtool maybe does that gcc won't?

**Comment by Vollstrecker** [comment]
I don't get it. even objdump tells me it's there. EXPORT_SPEC should'nt matter as it's empty on linux.

**Pull request closed without merging**
