### PR TITLE
Reactivate gtest

### PR DESCRIPTION
**Pull request by Vollstrecker**
Put it back all together. Mac works, win not. I left it in there, maybe some can see what goes wrong, but I guess it's the old "Win-is-not-for-networking-designed"-thing.

But it's always a pleasure to see Linux and Mac finished everything while windows is still setting up so it can start the configure.

### CODE REVIEW

**Comment by mrjimenez** [comment]
Nice! I must admit that lately some tests that failed on win32 were actually quite productive.

Lets see if we can put it to work.

**Comment by Vollstrecker** [comment]
This time I doubt that. I can't see any error, looks like the build itself just died quietly.

**Comment by mrjimenez** [comment]
Look again:

```bash
  Building Custom Rule D:/a/pupnp/pupnp/upnp/test/CMakeLists.txt
  test_url.c
  test-upnp-url-static.vcxproj -> D:\a\pupnp\pupnp\build\upnp\test\Debug\test-upnp-url-static.exe
  Building Custom Rule D:/a/pupnp/pupnp/gtest/CMakeLists.txt
  test_UpnpHttpHeaderList.cpp
gmockd.lib(gtest-all.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in test_UpnpHttpHeaderList.obj [D:\a\pupnp\pupnp\build\gtest\test_UpnpHttpHeaderList.vcxproj]
msvcprtd.lib(MSVCP140D.dll) : error LNK2005: "public: struct _Cvtvec __cdecl std::_Locinfo::_Getcvt(void)const " (?_Getcvt@_Locinfo@std@@QEBA?AU_Cvtvec@@XZ) already defined in gmockd.lib(gtest-all.obj) [D:\a\pupnp\pupnp\build\gtest\test_UpnpHttpHeaderList.vcxproj]
msvcprtd.lib(MSVCP140D.dll) : error LNK2005: "public: bool __cdecl std::ios_base::good(void)const " (?good@ios_base@std@@QEBA_NXZ) already defined in gmockd.lib(gtest-all.obj) [D:\a\pupnp\pupnp\build\gtest\test_UpnpHttpHeaderList.vcxproj]
msvcprtd.lib(MSVCP140D.dll) : error LNK2005: "public: int __cdecl std::ios_base::flags(void)const " (?flags@ios_base@std@@QEBAHXZ) already defined in gmockd.lib(gtest-all.obj) [D:\a\pupnp\pupnp\build\gtest\test_UpnpHttpHeaderList.vcxproj]
msvcprtd.lib(MSVCP140D.dll) : error LNK2005: "public: __int64 __cdecl std::ios_base::width(void)const " (?width@ios_base@std@@QEBA_JXZ) already defined in gmockd.lib(gtest-all.obj) [D:\a\pupnp\pupnp\build\gtest\test_UpnpHttpHeaderList.vcxproj]
msvcprtd.lib(MSVCP140D.dll) : error LNK2005: "public: __int64 __cdecl std::ios_base::width(__int64)" (?width@ios_base@std@@QEAA_J_J@Z) already defined in gmockd.lib(gtest-all.obj) [D:\a\pupnp\pupnp\build\gtest\test_UpnpHttpHeaderList.vcxproj]
msvcprtd.lib(MSVCP140D.dll) : error LNK2005: "protected: __cdecl std::basic_streambuf<char,struct std::char_traits<char> >::basic_streambuf<char,struct std::char_traits<char> >(void)" (??0?$basic_streambuf@DU?$char_traits@D@std@@@std@@IEAA@XZ) already defined in gmockd.lib(gtest-all.obj) [D:\a\pupnp\pupnp\build\gtest\test_UpnpHttpHeaderList.vcxproj]
msvcprtd.lib(MSVCP140D.dll) : error LNK2005: "public: virtual __cdecl std::basic_streambuf<char,struct std::char_traits<char> >::~basic_streambuf<char,struct std::char_traits<char> >(void)" (??1?$basic_streambuf@DU?$char_traits@D@std@@@std@@UEAA@XZ) already defined in gmockd.lib(gtest-all.obj) [D:\a\pupnp\pupnp\build\gtest\test_UpnpHttpHeaderList.vcxproj]
msvcprtd.lib(MSVCP140D.dll) : error LNK2005: "public: int __cdecl std::basic_streambuf<char,struct std::char_traits<char> >::sputc(char)" (?sputc@?$basic_streambuf@DU?$char_traits@D@std@@@std@@QEAAHD@Z) already defined in gmockd.lib(gtest-all.obj) [D:\a\pupnp\pupnp\build\gtest\test_UpnpHttpHeaderList.vcxproj]
msvcprtd.lib(MSVCP140D.dll) : error LNK2005: "public: __int64 __cdecl std::basic_streambuf<char,struct std::char_traits<char> >::sputn(char const *,__int64)" (?sputn@?$basic_streambuf@DU?$char_traits@D@std@@@std@@QEAA_JPEBD_J@Z) already defined in gmockd.lib(gtest-all.obj) [D:\a\pupnp\pupnp\build\gtest\test_UpnpHttpHeaderList.vcxproj]
msvcprtd.lib(MSVCP140D.dll) : error LNK2005: "protected: char * __cdecl std::basic_streambuf<char,struct std::char_traits<char> >::eback(void)const " (?eback@?$basic_streambuf@DU?$char_traits@D@std@@@std@@IEBAPEADXZ) already defined in gmockd.lib(gtest-all.obj) [D:\a\pupnp\pupnp\build\gtest\test_UpnpHttpHeaderList.vcxproj]
msvcprtd.lib(MSVCP140D.dll) : error LNK2005: "protected: char * __cdecl std::basic_streambuf<char,struct std::char_traits<char> >::gptr(void)const " (?gptr@?$basic_streambuf@DU?$char_traits@D@std@@@std@@IEBAPEADXZ) already defined in gmockd.lib(gtest-all.obj) [D:\a\pupnp\pupnp\build\gtest\test_UpnpHttpHeaderList.vcxproj]
msvcprtd.lib(MSVCP140D.dll) : error LNK2005: "protected: char * __cdecl std::basic_streambuf<char,struct std::char_traits<char> >::pbase(void)const " (?pbase@?$basic_streambuf@DU?$char_traits@D@std@@@std@@IEBAPEADXZ) already defined in gmockd.lib(gtest-all.obj) [D:\a\pupnp\pupnp\build\gtest\test_UpnpHttpHeaderList.vcxproj]
msvcprtd.lib(MSVCP140D.dll) : error LNK2005: "protected: char * __cdecl std::basic_streambuf<char,struct std::char_traits<char> >::pptr(void)const " (?pptr@?$basic_streambuf@DU?$char_traits@D@std@@@std@@IEBAPEADXZ) already defined in gmockd.lib(gtest-all.obj) [D:\a\pupnp\pupnp\build\gtest\test_UpnpHttpHeaderList.vcxproj]
msvcprtd.lib(MSVCP140D.dll) : error LNK2005: "protected: char * __cdecl std::basic_streambuf<char,struct std::char_traits<char> >::egptr(void)const " (?egptr@?$basic_streambuf@DU?$char_traits@D@std@@@std@@IEBAPEADXZ) already defined in gmockd.lib(gtest-all.obj) [D:\a\pupnp\pupnp\build\gtest\test_UpnpHttpHeaderList.vcxproj]
msvcprtd.lib(MSVCP140D.dll) : error LNK2005: "protected: void __cdecl std::basic_streambuf<char,struct std::char_traits<char> >::gbump(int)" (?gbump@?$basic_streambuf@DU?$char_traits@D@std@@@std@@IEAAXH@Z) already defined in gmockd.lib(gtest-all.obj) [D:\a\pupnp\pupnp\build\gtest\test_UpnpHttpHeaderList.vcxproj]
msvcprtd.lib(MSVCP140D.dll) : error LNK2005: "protected: void __cdecl std::basic_streambuf<char,struct std::char_traits<char> >::setg(char *,char *,char *)" (?setg@?$basic_streambuf@DU?$char_traits@D@std@@@std@@IEAAXPEAD00@Z) already defined in gmockd.lib(gtest-all.obj) [D:\a\pupnp\pupnp\build\gtest\test_UpnpHttpHeaderList.vcxproj]
msvcprtd.lib(MSVCP140D.dll) : error LNK2005: "protected: char * __cdecl std::basic_streambuf<char,struct std::char_traits<char> >::epptr(void)const " (?epptr@?$basic_streambuf@DU?$char_traits@D@std@@@std@@IEBAPEADXZ) already defined in gmockd.lib(gtest-all.obj) [D:\a\pupnp\pupnp\build\gtest\test_UpnpHttpHeaderList.vcxproj]
msvcprtd.lib(MSVCP140D.dll) : error LNK2005: "protected: void __cdecl std::basic_streambuf<char,struct std::char_traits<char> >::setp(char *,char *)" (?setp@?$basic_streambuf@DU?$char_traits@D@std@@@std@@IEAAXPEAD0@Z) already defined in gmockd.lib(gtest-all.obj) [D:\a\pupnp\pupnp\build\gtest\test_UpnpHttpHeaderList.vcxproj]
msvcprtd.lib(MSVCP140D.dll) : error LNK2005: "protected: void __cdecl std::basic_streambuf<char,struct std::char_traits<char> >::setp(char *,char *,char *)" (?setp@?$basic_streambuf@DU?$char_traits@D@std@@@std@@IEAAXPEAD00@Z) already defined in gmockd.lib(gtest-all.obj) [D:\a\pupnp\pupnp\build\gtest\test_UpnpHttpHeaderList.vcxproj]
msvcprtd.lib(MSVCP140D.dll) : error LNK2005: "protected: char * __cdecl std::basic_streambuf<char,struct std::char_traits<char> >::_Pninc(void)" (?_Pninc@?$basic_streambuf@DU?$char_traits@D@std@@@std@@IEAAPEADXZ) already defined in gmockd.lib(gtest-all.obj) [D:\a\pupnp\pupnp\build\gtest\test_UpnpHttpHeaderList.vcxproj]
msvcprtd.lib(MSVCP140D.dll) : error LNK2005: "public: virtual __cdecl std::basic_ios<char,struct std::char_traits<char> >::~basic_ios<char,struct std::char_traits<char> >(void)" (??1?$basic_ios@DU?$char_traits@D@std@@@std@@UEAA@XZ) already defined in gmockd.lib(gtest-all.obj) [D:\a\pupnp\pupnp\build\gtest\test_UpnpHttpHeaderList.vcxproj]
msvcprtd.lib(MSVCP140D.dll) : error LNK2005: "public: void __cdecl std::basic_ios<char,struct std::char_traits<char> >::setstate(int,bool)" (?setstate@?$basic_ios@DU?$char_traits@D@std@@@std@@QEAAXH_N@Z) already defined in gmockd.lib(gtest-all.obj) [D:\a\pupnp\pupnp\build\gtest\test_UpnpHttpHeaderList.vcxproj]
msvcprtd.lib(MSVCP140D.dll) : error LNK2005: "public: class std::basic_ostream<char,struct std::char_traits<char> > * __cdecl std::basic_ios<char,struct std::char_traits<char> >::tie(void)const " (?tie@?$basic_ios@DU?$char_traits@D@std@@@std@@QEBAPEAV?$basic_ostream@DU?$char_traits@D@std@@@2@XZ) already defined in gmockd.lib(gtest-all.obj) [D:\a\pupnp\pupnp\build\gtest\test_UpnpHttpHeaderList.vcxproj]
msvcprtd.lib(MSVCP140D.dll) : error LNK2005: "public: class std::basic_streambuf<char,struct std::char_traits<char> > * __cdecl std::basic_ios<char,struct std::char_traits<char> >::rdbuf(void)const " (?rdbuf@?$basic_ios@DU?$char_traits@D@std@@@std@@QEBAPEAV?$basic_streambuf@DU?$char_traits@D@std@@@2@XZ) already defined in gmockd.lib(gtest-all.obj) [D:\a\pupnp\pupnp\build\gtest\test_UpnpHttpHeaderList.vcxproj]
msvcprtd.lib(MSVCP140D.dll) : error LNK2005: "public: char __cdecl std::basic_ios<char,struct std::char_traits<char> >::fill(void)const " (?fill@?$basic_ios@DU?$char_traits@D@std@@@std@@QEBADXZ) already defined in gmockd.lib(gtest-all.obj) [D:\a\pupnp\pupnp\build\gtest\test_UpnpHttpHeaderList.vcxproj]
msvcprtd.lib(MSVCP140D.dll) : error LNK2005: "protected: __cdecl std::basic_ios<char,struct std::char_traits<char> >::basic_ios<char,struct std::char_traits<char> >(void)" (??0?$basic_ios@DU?$char_traits@D@std@@@std@@IEAA@XZ) already defined in gmockd.lib(gtest-all.obj) [D:\a\pupnp\pupnp\build\gtest\test_UpnpHttpHeaderList.vcxproj]
msvcprtd.lib(MSVCP140D.dll) : error LNK2005: "public: void __cdecl std::basic_ostream<char,struct std::char_traits<char> >::_Osfx(void)" (?_Osfx@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAAXXZ) already defined in gmockd.lib(gtest-all.obj) [D:\a\pupnp\pupnp\build\gtest\test_UpnpHttpHeaderList.vcxproj]
msvcprtd.lib(MSVCP140D.dll) : error LNK2005: "public: class std::basic_ostream<char,struct std::char_traits<char> > & __cdecl std::basic_ostream<char,struct std::char_traits<char> >::operator<<(int)" (??6?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAAAEAV01@H@Z) already defined in gmockd.lib(gtest-all.obj) [D:\a\pupnp\pupnp\build\gtest\test_UpnpHttpHeaderList.vcxproj]
msvcprtd.lib(MSVCP140D.dll) : error LNK2005: "public: class std::basic_ostream<char,struct std::char_traits<char> > & __cdecl std::basic_ostream<char,struct std::char_traits<char> >::operator<<(unsigned __int64)" (??6?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAAAEAV01@_K@Z) already defined in gmockd.lib(gtest-all.obj) [D:\a\pupnp\pupnp\build\gtest\test_UpnpHttpHeaderList.vcxproj]
msvcprtd.lib(MSVCP140D.dll) : error LNK2005: "public: class std::basic_ostream<char,struct std::char_traits<char> > & __cdecl std::basic_ostream<char,struct std::char_traits<char> >::operator<<(void const *)" (??6?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAAAEAV01@PEBX@Z) already defined in gmockd.lib(gtest-all.obj) [D:\a\pupnp\pupnp\build\gtest\test_UpnpHttpHeaderList.vcxproj]
msvcprtd.lib(MSVCP140D.dll) : error LNK2005: "public: class std::basic_ostream<char,struct std::char_traits<char> > & __cdecl std::basic_ostream<char,struct std::char_traits<char> >::flush(void)" (?flush@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAAAEAV12@XZ) already defined in gmockd.lib(gtest-all.obj) [D:\a\pupnp\pupnp\build\gtest\test_UpnpHttpHeaderList.vcxproj]
msvcprtd.lib(MSVCP140D.dll) : error LNK2005: "public: __cdecl std::basic_iostream<char,struct std::char_traits<char> >::basic_iostream<char,struct std::char_traits<char> >(class std::basic_streambuf<char,struct std::char_traits<char> > *)" (??0?$basic_iostream@DU?$char_traits@D@std@@@std@@QEAA@PEAV?$basic_streambuf@DU?$char_traits@D@std@@@1@@Z) already defined in gmockd.lib(gtest-all.obj) [D:\a\pupnp\pupnp\build\gtest\test_UpnpHttpHeaderList.vcxproj]
msvcprtd.lib(MSVCP140D.dll) : error LNK2005: "public: virtual __cdecl std::basic_iostream<char,struct std::char_traits<char> >::~basic_iostream<char,struct std::char_traits<char> >(void)" (??1?$basic_iostream@DU?$char_traits@D@std@@@std@@UEAA@XZ) already defined in gmockd.lib(gtest-all.obj) [D:\a\pupnp\pupnp\build\gtest\test_UpnpHttpHeaderList.vcxproj]
libcpmtd.lib(locale0.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in test_UpnpHttpHeaderList.obj [D:\a\pupnp\pupnp\build\gtest\test_UpnpHttpHeaderList.vcxproj]
libcpmtd.lib(locale0.obj) : error LNK2005: "void __cdecl std::_Facet_Register(class std::_Facet_base *)" (?_Facet_Register@std@@YAXPEAV_Facet_base@1@@Z) already defined in msvcprtd.lib(locale0_implib.obj) [D:\a\pupnp\pupnp\build\gtest\test_UpnpHttpHeaderList.vcxproj]
libcpmtd.lib(locale0.obj) : error LNK2005: "private: static class std::locale::_Locimp * __cdecl std::locale::_Getgloballocale(void)" (?_Getgloballocale@locale@std@@CAPEAV_Locimp@12@XZ) already defined in msvcprtd.lib(MSVCP140D.dll) [D:\a\pupnp\pupnp\build\gtest\test_UpnpHttpHeaderList.vcxproj]
libcpmtd.lib(locale0.obj) : error LNK2005: "private: static class std::locale::_Locimp * __cdecl std::locale::_Init(bool)" (?_Init@locale@std@@CAPEAV_Locimp@12@_N@Z) already defined in msvcprtd.lib(MSVCP140D.dll) [D:\a\pupnp\pupnp\build\gtest\test_UpnpHttpHeaderList.vcxproj]
libcpmtd.lib(locale0.obj) : error LNK2005: "public: static void __cdecl std::_Locinfo::_Locinfo_ctor(class std::_Locinfo *,char const *)" (?_Locinfo_ctor@_Locinfo@std@@SAXPEAV12@PEBD@Z) already defined in msvcprtd.lib(MSVCP140D.dll) [D:\a\pupnp\pupnp\build\gtest\test_UpnpHttpHeaderList.vcxproj]
libcpmtd.lib(locale0.obj) : error LNK2005: "public: static void __cdecl std::_Locinfo::_Locinfo_dtor(class std::_Locinfo *)" (?_Locinfo_dtor@_Locinfo@std@@SAXPEAV12@@Z) already defined in msvcprtd.lib(MSVCP140D.dll) [D:\a\pupnp\pupnp\build\gtest\test_UpnpHttpHeaderList.vcxproj]
libcpmtd.lib(locale0.obj) : error LNK2005: "private: static class std::locale::_Locimp * __cdecl std::locale::_Locimp::_New_Locimp(class std::locale::_Locimp const &)" (?_New_Locimp@_Locimp@locale@std@@CAPEAV123@AEBV123@@Z) already defined in msvcprtd.lib(MSVCP140D.dll) [D:\a\pupnp\pupnp\build\gtest\test_UpnpHttpHeaderList.vcxproj]
libcpmtd.lib(cout.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in test_UpnpHttpHeaderList.obj [D:\a\pupnp\pupnp\build\gtest\test_UpnpHttpHeaderList.vcxproj]
libcpmtd.lib(cerr.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in test_UpnpHttpHeaderList.obj [D:\a\pupnp\pupnp\build\gtest\test_UpnpHttpHeaderList.vcxproj]
libcpmtd.lib(locale.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in test_UpnpHttpHeaderList.obj [D:\a\pupnp\pupnp\build\gtest\test_UpnpHttpHeaderList.vcxproj]
libcpmtd.lib(locale.obj) : error LNK2005: "private: static void __cdecl std::locale::_Locimp::_Locimp_Addfac(class std::locale::_Locimp *,class std::locale::facet *,unsigned __int64)" (?_Locimp_Addfac@_Locimp@locale@std@@CAXPEAV123@PEAVfacet@23@_K@Z) already defined in msvcprtd.lib(MSVCP140D.dll) [D:\a\pupnp\pupnp\build\gtest\test_UpnpHttpHeaderList.vcxproj]
libcpmtd.lib(iosptrs.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in test_UpnpHttpHeaderList.obj [D:\a\pupnp\pupnp\build\gtest\test_UpnpHttpHeaderList.vcxproj]
libcpmtd.lib(xlock.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in test_UpnpHttpHeaderList.obj [D:\a\pupnp\pupnp\build\gtest\test_UpnpHttpHeaderList.vcxproj]
libcpmtd.lib(xlock.obj) : error LNK2005: "public: __cdecl std::_Lockit::_Lockit(int)" (??0_Lockit@std@@QEAA@H@Z) already defined in msvcprtd.lib(MSVCP140D.dll) [D:\a\pupnp\pupnp\build\gtest\test_UpnpHttpHeaderList.vcxproj]
libcpmtd.lib(xlock.obj) : error LNK2005: "public: __cdecl std::_Lockit::~_Lockit(void)" (??1_Lockit@std@@QEAA@XZ) already defined in msvcprtd.lib(MSVCP140D.dll) [D:\a\pupnp\pupnp\build\gtest\test_UpnpHttpHeaderList.vcxproj]
libcpmtd.lib(wlocale.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in test_UpnpHttpHeaderList.obj [D:\a\pupnp\pupnp\build\gtest\test_UpnpHttpHeaderList.vcxproj]
libcpmtd.lib(wlocale.obj) : error LNK2005: "public: char const * __cdecl std::_Locinfo::_Getdays(void)const " (?_Getdays@_Locinfo@std@@QEBAPEBDXZ) already defined in msvcprtd.lib(MSVCP140D.dll) [D:\a\pupnp\pupnp\build\gtest\test_UpnpHttpHeaderList.vcxproj]
libcpmtd.lib(wlocale.obj) : error LNK2005: "public: char const * __cdecl std::_Locinfo::_Getmonths(void)const " (?_Getmonths@_Locinfo@std@@QEBAPEBDXZ) already defined in msvcprtd.lib(MSVCP140D.dll) [D:\a\pupnp\pupnp\build\gtest\test_UpnpHttpHeaderList.vcxproj]
libcpmtd.lib(wlocale.obj) : error LNK2005: "public: unsigned short const * __cdecl std::_Locinfo::_W_Getdays(void)const " (?_W_Getdays@_Locinfo@std@@QEBAPEBGXZ) already defined in msvcprtd.lib(MSVCP140D.dll) [D:\a\pupnp\pupnp\build\gtest\test_UpnpHttpHeaderList.vcxproj]
libcpmtd.lib(wlocale.obj) : error LNK2005: "public: unsigned short const * __cdecl std::_Locinfo::_W_Getmonths(void)const " (?_W_Getmonths@_Locinfo@std@@QEBAPEBGXZ) already defined in msvcprtd.lib(MSVCP140D.dll) [D:\a\pupnp\pupnp\build\gtest\test_UpnpHttpHeaderList.vcxproj]
libcpmtd.lib(xlocale.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in test_UpnpHttpHeaderList.obj [D:\a\pupnp\pupnp\build\gtest\test_UpnpHttpHeaderList.vcxproj]
libcpmtd.lib(xlocale.obj) : error LNK2005: "public: char const * __cdecl std::_Locinfo::_Getdays(void)const " (?_Getdays@_Locinfo@std@@QEBAPEBDXZ) already defined in msvcprtd.lib(MSVCP140D.dll) [D:\a\pupnp\pupnp\build\gtest\test_UpnpHttpHeaderList.vcxproj]
libcpmtd.lib(xlocale.obj) : error LNK2005: "public: char const * __cdecl std::_Locinfo::_Getmonths(void)const " (?_Getmonths@_Locinfo@std@@QEBAPEBDXZ) already defined in msvcprtd.lib(MSVCP140D.dll) [D:\a\pupnp\pupnp\build\gtest\test_UpnpHttpHeaderList.vcxproj]
libcpmtd.lib(xlocale.obj) : error LNK2005: "public: unsigned short const * __cdecl std::_Locinfo::_W_Getdays(void)const " (?_W_Getdays@_Locinfo@std@@QEBAPEBGXZ) already defined in msvcprtd.lib(MSVCP140D.dll) [D:\a\pupnp\pupnp\build\gtest\test_UpnpHttpHeaderList.vcxproj]
libcpmtd.lib(xlocale.obj) : error LNK2005: "public: unsigned short const * __cdecl std::_Locinfo::_W_Getmonths(void)const " (?_W_Getmonths@_Locinfo@std@@QEBAPEBGXZ) already defined in msvcprtd.lib(MSVCP140D.dll) [D:\a\pupnp\pupnp\build\gtest\test_UpnpHttpHeaderList.vcxproj]
libcpmtd.lib(xstol.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in test_UpnpHttpHeaderList.obj [D:\a\pupnp\pupnp\build\gtest\test_UpnpHttpHeaderList.vcxproj]
libcpmtd.lib(xstoul.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in test_UpnpHttpHeaderList.obj [D:\a\pupnp\pupnp\build\gtest\test_UpnpHttpHeaderList.vcxproj]
libcpmtd.lib(xstoll.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in test_UpnpHttpHeaderList.obj [D:\a\pupnp\pupnp\build\gtest\test_UpnpHttpHeaderList.vcxproj]
libcpmtd.lib(xstoull.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in test_UpnpHttpHeaderList.obj [D:\a\pupnp\pupnp\build\gtest\test_UpnpHttpHeaderList.vcxproj]
libcpmtd.lib(xmtx.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in test_UpnpHttpHeaderList.obj [D:\a\pupnp\pupnp\build\gtest\test_UpnpHttpHeaderList.vcxproj]
libcpmtd.lib(xstrcoll.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in test_UpnpHttpHeaderList.obj [D:\a\pupnp\pupnp\build\gtest\test_UpnpHttpHeaderList.vcxproj]
libcpmtd.lib(xdateord.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in test_UpnpHttpHeaderList.obj [D:\a\pupnp\pupnp\build\gtest\test_UpnpHttpHeaderList.vcxproj]
libcpmtd.lib(xwcscoll.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in test_UpnpHttpHeaderList.obj [D:\a\pupnp\pupnp\build\gtest\test_UpnpHttpHeaderList.vcxproj]
libcpmtd.lib(xwcsxfrm.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in test_UpnpHttpHeaderList.obj [D:\a\pupnp\pupnp\build\gtest\test_UpnpHttpHeaderList.vcxproj]
libcpmtd.lib(xgetwctype.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in test_UpnpHttpHeaderList.obj [D:\a\pupnp\pupnp\build\gtest\test_UpnpHttpHeaderList.vcxproj]
libcpmtd.lib(xtowlower.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in test_UpnpHttpHeaderList.obj [D:\a\pupnp\pupnp\build\gtest\test_UpnpHttpHeaderList.vcxproj]
libcpmtd.lib(xtowupper.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in test_UpnpHttpHeaderList.obj [D:\a\pupnp\pupnp\build\gtest\test_UpnpHttpHeaderList.vcxproj]
libcpmtd.lib(xstrxfrm.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in test_UpnpHttpHeaderList.obj [D:\a\pupnp\pupnp\build\gtest\test_UpnpHttpHeaderList.vcxproj]
libcpmtd.lib(StlCompareStringA.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in test_UpnpHttpHeaderList.obj [D:\a\pupnp\pupnp\build\gtest\test_UpnpHttpHeaderList.vcxproj]
libcpmtd.lib(StlCompareStringW.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in test_UpnpHttpHeaderList.obj [D:\a\pupnp\pupnp\build\gtest\test_UpnpHttpHeaderList.vcxproj]
libcpmtd.lib(StlLCMapStringW.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in test_UpnpHttpHeaderList.obj [D:\a\pupnp\pupnp\build\gtest\test_UpnpHttpHeaderList.vcxproj]
libcpmtd.lib(StlLCMapStringA.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in test_UpnpHttpHeaderList.obj [D:\a\pupnp\pupnp\build\gtest\test_UpnpHttpHeaderList.vcxproj]
LINK : warning LNK4098: defaultlib 'LIBCMTD' conflicts with use of other libs; use /NODEFAULTLIB:library [D:\a\pupnp\pupnp\build\gtest\test_UpnpHttpHeaderList.vcxproj]
D:\a\pupnp\pupnp\build\gtest\Debug\test_UpnpHttpHeaderList.exe : fatal error LNK1169: one or more multiply defined symbols found [D:\a\pupnp\pupnp\build\gtest\test_UpnpHttpHeaderList.vcxproj]
  Building Custom Rule D:/a/pupnp/pupnp/gtest/CMakeLists.txt
  test_UpnpHttpHeaderList.cpp
gmockd.lib(gtest-all.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in test_UpnpHttpHeaderList.obj [D:\a\pupnp\pupnp\build\gtest\test_UpnpHttpHeaderList-static.vcxproj]
```

Ok, I will consider fixing those win32 warnings so that we can read this stuff more easily.

**Comment by Vollstrecker** [comment]
k, then I know the problem. I have to cook now, but if it's the only thing, this is easy to fix.

**Comment by mrjimenez** [comment]
Sure, take your time.

**Comment by Vollstrecker** [comment]
google let's cmake detect the right values and then messes with the global flags wrapped in an if not a and not b.
I hate when they do that, but now it works.

**Comment by mrjimenez** [comment]
I see that all tests pass here. I will commit.

**Pull request merged**
